services:
  database:
    image: postgres:17
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.backend
    container_name: backend_container
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TREFLE_API_KEY: ${TREFLE_API_KEY}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ../backend/logs:/app/logs
      - ../backend/image:/app/image
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../frontend/build/web:/usr/share/nginx/html:ro

volumes:
  postgres_data:
  image_data:
